In [1]:
%matplotlib inline
import sympy as sympy           # provides symbolic computation (solving algebra problems)
import numpy as np              # provides linear algebra computations
import matplotlib.pyplot as plt # graph functions and draw figures
import seaborn as sbn           # prettier matplotlib figures
from scipy import *             # scientific python 

In [4]:
# Creating arrays, scalars and matrices in Python 
x = 0.5 # creating a scalar
print x

0.5


In [8]:
# Vectors and lists, numpy (np) is the core library for linear algebra.
# lists in python are NOT arrays. 
x_vector = np.array([1,2,3]) # creating a vector
print x_vector
print "Has shape:", x_vector.shape
print type(x_vector)

[1 2 3]
Has shape: (3,)
<type 'numpy.ndarray'>


In [12]:
# Matrices
c = [1, 2]
z = [5, 6]
b = zip(z, c)
print b  # this is still a list not a matrix yet.

# Convert list to an Matrix
A = np.array(b)
print A
print type(A)
print "A has shape: ", A.shape

[(5, 1), (6, 2)]
[[5 1]
 [6 2]]
<type 'numpy.ndarray'>
A has shape:  (2, 2)


In [14]:
# Matrix Addition and Subtraction
# adding/subtracting a scalar to each element in the matrix
add = A + 3 
sub = A - 3 
print add
print sub

[[8 4]
 [9 5]]
[[ 2 -2]
 [ 3 -1]]


In [19]:
# Adding or subtracting two Matrices
B = np.random.randn(2, 2) # create a matrix with random numbers
print A, " + ",  B, "="
result = A + B
result

[[5 1]
 [6 2]]  +  [[-0.3833986  -0.18918062]
 [-0.88850113 -0.00955464]] =


array([[ 4.6166014 ,  0.81081938],
       [ 5.11149887,  1.99044536]])

In [24]:
# Matrix Multiplication
mult = A * 3 # mutliply by a scalar
mult

# Multiply two matricies
A = np.arange(6).reshape((3,2))
C = np.random.randn(2,2)   
print A
print C
print A.shape
print C.shape

# We can use the numpy dot operator to perform these multiplications. 
# two ways to do it. 
print A.dot(C)
print np.dot(A,C)

# we can't multiply C * A because 2*2 and 3*2 the # of columns in C 
# don't match the number of rows in A. Results in a valueError

[[0 1]
 [2 3]
 [4 5]]
[[ 0.94047198 -1.47470871]
 [ 0.94544728 -0.51268769]]
(3, 2)
(2, 2)
[[ 0.94544728 -0.51268769]
 [ 4.71728581 -4.4874805 ]
 [ 8.48912433 -8.4622733 ]]
[[ 0.94544728 -0.51268769]
 [ 4.71728581 -4.4874805 ]
 [ 8.48912433 -8.4622733 ]]


In [32]:
# Example Application of matrix multiplication to predict housing prices
# Hypothesis : h(x) = -40 +0.25x
a = (1, 1, 1, 1)            
b = (2104, 1416, 1534, 852) # housing prices
A = np.array(zip(a, b))
print A

coeffs = np.array([-40, 0.25])
prediction = np.dot(A, coeffs)
print prediction



[[   1 2104]
 [   1 1416]
 [   1 1534]
 [   1  852]]
[ 486.   314.   343.5  173. ]
