In [5]:
# Core Scientific Stack in python
%matplotlib inline
import sympy as sympy           # provides symbolic computation (solving algebra problems)
import numpy as np              # provides linear algebra computations
import matplotlib.pyplot as plt # graph functions and draw figures
import seaborn as sbn           # prettier matplotlib figures
from scipy import *             # scientific python 

#### Creating arrays, scalars and matrices in Python 

In [6]:
x = 0.5 # creating a scalar
print x

0.5


In [7]:
# Vectors and lists, numpy (np) is the core library for linear algebra.
# lists in python are NOT arrays. 
x_vector = np.array([1,2,3]) # creating a vector
print x_vector
print "Has shape:", x_vector.shape
print type(x_vector)

[1 2 3]
Has shape: (3,)
<type 'numpy.ndarray'>


In [8]:
# Matrices
c = [1, 2]
z = [5, 6]
b = zip(z, c)
print b  # this is still a list not a matrix yet.

# Convert list to an Matrix
A = np.array(b)
print A
print type(A)
print "A has shape: ", A.shape

[(5, 1), (6, 2)]
[[5 1]
 [6 2]]
<type 'numpy.ndarray'>
A has shape:  (2, 2)


#### Matrix Addition and Subtraction

In [9]:
# adding/subtracting a scalar to each element in the matrix
add = A + 3 
sub = A - 3 
print add
print sub

[[8 4]
 [9 5]]
[[ 2 -2]
 [ 3 -1]]


In [10]:
# Adding or subtracting two Matrices
B = np.random.randn(2, 2) # create a matrix with random numbers
print A, " + ",  B, "="
result = A + B
result

[[5 1]
 [6 2]]  +  [[ 1.11813807  0.26580438]
 [-0.13753815  0.06348561]] =


array([[ 6.11813807,  1.26580438],
       [ 5.86246185,  2.06348561]])

#### Matrix Multiplication

In [11]:
mult = A * 3 # mutliply by a scalar
mult

# Multiply two matricies
A = np.arange(6).reshape((3,2))
C = np.random.randn(2,2)   
print A
print C
print A.shape
print C.shape

# We can use the numpy dot operator to perform these multiplications. 
# two ways to do it. 
print A.dot(C)
print np.dot(A,C)

# we can't multiply C * A because 2*2 and 3*2 the # of columns in C 
# don't match the number of rows in A. Results in a valueError

[[0 1]
 [2 3]
 [4 5]]
[[-0.08030093  0.04861546]
 [ 0.12265275 -0.2581282 ]]
(3, 2)
(2, 2)
[[ 0.12265275 -0.2581282 ]
 [ 0.20735638 -0.67715368]
 [ 0.29206001 -1.09617916]]
[[ 0.12265275 -0.2581282 ]
 [ 0.20735638 -0.67715368]
 [ 0.29206001 -1.09617916]]


#### Example Application

In [12]:
# Using matrix multiplication to predict housing prices
# Hypothesis : h(x) = -40 +0.25x
a = (1, 1, 1, 1)            
b = (2104, 1416, 1534, 852) # housing prices
A = np.array(zip(a, b))
print A

coeffs = np.array([-40, 0.25])
prediction = np.dot(A, coeffs)
print prediction



[[   1 2104]
 [   1 1416]
 [   1 1534]
 [   1  852]]
[ 486.   314.   343.5  173. ]


#### Computing the Inverse of a matrix

In [13]:
# in order to compute the inverse we must hava square matrix
# where # rows = # cols. 
# Here C is a 2*2 randomly genrated matrix
C_inverse = np.linalg.inv(C)
print C_inverse

[[-17.48230165  -3.29258925]
 [ -8.30692792  -5.43855776]]


In [15]:
# check that C * C ^-1 = I
print C.dot(C_inverse)
print "Is identical to:"
print C_inverse.dot(C)

[[  1.00000000e+00   5.55111512e-17]
 [  0.00000000e+00   1.00000000e+00]]
Is identical to:
[[  1.00000000e+00   2.22044605e-16]
 [ -1.11022302e-16   1.00000000e+00]]


#### Transposing a Matrix

In [17]:
A = np.arange(6).reshape((3, 2))
B = np.arange(8).reshape((2, 4))

print "A is"
print A

print "The transpose of A is"
print A.T

A is
[[0 1]
 [2 3]
 [4 5]]
The transpose of A is
[[0 2 4]
 [1 3 5]]


In [19]:
print B.T.dot(A.T)    # A'*B'
print "Is Identical to:"
print (A.dot(B).T)    # (A*B)'

[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]
Is Identical to:
[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]


In [22]:
# Slicing
print A
A[:,0]

# grabbing a single element
A[2,1]


[[0 1]
 [2 3]
 [4 5]]


5

In [26]:
A = np.arange(24).reshape((12,2))
print A
print A.shape

for rows in A:
    print rows

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
(12, 2)
[0 1]
[2 3]
[4 5]
[6 7]
[8 9]
[10 11]
[12 13]
[14 15]
[16 17]
[18 19]
[20 21]
[22 23]


In [27]:
for cols in A.T:
    print cols

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[ 1  3  5  7  9 11 13 15 17 19 21 23]
